In [314]:
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
from scipy import stats
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report,confusion_matrix

In [ ]:
def Adult_data_preprocessing():
    col = ['age','workclass','fnlwgt','education','education-num','marital-status','occupation','relationship','race','sex',
       'capital-gain','capital-loss','hours-per-week','native-country','salary']
    data = pd.read_csv("adult.data")
    categorical_columns = ['workclass','education','marital-status','occupation','relationship','race','sex','native-country','salary']
    for i in categorical_columns:
    data[i] = pd.Categorical(data[i]).codes
    data.columns = data.columns.str.lstrip()
    a = StandardScaler()
    X = data.drop(['salary'],axis=1)
    X = a.fit_transform(X)
    y = data['salary']
    X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=0,test_size=0.3)
    train_models(X_train,X_test,y_train,y_test)

In [280]:
col = ['age','workclass','fnlwgt','education','education-num','marital-status','occupation','relationship','race','sex',
       'capital-gain','capital-loss','hours-per-week','native-country','salary']

In [281]:
data = pd.read_csv("adult.data")

In [235]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32560 entries, 0 to 32559
Data columns (total 15 columns):
39                32560 non-null int64
 State-gov        32560 non-null object
 77516            32560 non-null int64
 Bachelors        32560 non-null object
 13               32560 non-null int64
 Never-married    32560 non-null object
 Adm-clerical     32560 non-null object
 Not-in-family    32560 non-null object
 White            32560 non-null object
 Male             32560 non-null object
 2174             32560 non-null int64
 0                32560 non-null int64
 40               32560 non-null int64
 United-States    32560 non-null object
 <=50K            32560 non-null object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB


In [282]:
data.columns=col

In [283]:
data.head(n=5)

age          workclass  fnlwgt   education  education-num  \
0   50   Self-emp-not-inc   83311   Bachelors             13   
1   38            Private  215646     HS-grad              9   
2   53            Private  234721        11th              7   
3   28            Private  338409   Bachelors             13   
4   37            Private  284582     Masters             14   

        marital-status          occupation    relationship    race      sex  \
0   Married-civ-spouse     Exec-managerial         Husband   White     Male   
1             Divorced   Handlers-cleaners   Not-in-family   White     Male   
2   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
3   Married-civ-spouse      Prof-specialty            Wife   Black   Female   
4   Married-civ-spouse     Exec-managerial            Wife   White   Female   

   capital-gain  capital-loss  hours-per-week  native-country  salary  
0             0             0              13   United-States   <=50K  
1             0             0              40   United-States   <=50K  
2             0             0              40   United-States   <=50K  
3             0             0              40            Cuba   <=50K  
4             0             0              40   United-States   <=50K

In [284]:
data['workclass'].unique()

array([' Self-emp-not-inc', ' Private', ' State-gov', ' Federal-gov',
       ' Local-gov', ' ?', ' Self-emp-inc', ' Without-pay',
       ' Never-worked'], dtype=object)

In [285]:
data.mean()

age                   38.581634
fnlwgt            189781.814373
education-num         10.080590
capital-gain        1077.615172
capital-loss          87.306511
hours-per-week        40.437469
dtype: float64

In [288]:
data[data['workclass']==' ?']

age workclass  fnlwgt      education  education-num  \
26      54         ?  180211   Some-college             10   
60      32         ?  293936        7th-8th              4   
68      25         ?  200681   Some-college             10   
76      67         ?  212759           10th              6   
105     17         ?  304873           10th              6   
...    ...       ...     ...            ...            ...   
32529   35         ?  320084      Bachelors             13   
32530   30         ?   33811      Bachelors             13   
32538   71         ?  287372      Doctorate             16   
32540   41         ?  202822        HS-grad              9   
32541   72         ?  129912        HS-grad              9   

               marital-status occupation    relationship                 race  \
26         Married-civ-spouse          ?         Husband   Asian-Pac-Islander   
60      Married-spouse-absent          ?   Not-in-family                White   
68              Never-married          ?       Own-child                White   
76         Married-civ-spouse          ?         Husband                White   
105             Never-married          ?       Own-child                White   
...                       ...        ...             ...                  ...   
32529      Married-civ-spouse          ?            Wife                White   
32530           Never-married          ?   Not-in-family   Asian-Pac-Islander   
32538      Married-civ-spouse          ?         Husband                White   
32540               Separated          ?   Not-in-family                Black   
32541      Married-civ-spouse          ?         Husband                White   

           sex  capital-gain  capital-loss  hours-per-week  native-country  \
26        Male             0             0              60           South   
60        Male             0             0              40               ?   
68        Male             0             0              40   United-States   
76        Male             0             0               2   United-States   
105     Female         34095             0              32   United-States   
...        ...           ...           ...             ...             ...   
32529   Female             0             0              55   United-States   
32530   Female             0             0              99   United-States   
32538     Male             0             0              10   United-States   
32540   Female             0             0              32   United-States   
32541     Male             0             0              25   United-States   

       salary  
26       >50K  
60      <=50K  
68      <=50K  
76      <=50K  
105     <=50K  
...       ...  
32529    >50K  
32530   <=50K  
32538    >50K  
32540   <=50K  
32541   <=50K  

[1836 rows x 15 columns]

In [289]:
data.iloc[26]

age                                54
workclass                           ?
fnlwgt                         180211
education                Some-college
education-num                      10
marital-status     Married-civ-spouse
occupation                          ?
relationship                  Husband
race               Asian-Pac-Islander
sex                              Male
capital-gain                        0
capital-loss                        0
hours-per-week                     60
native-country                  South
salary                           >50K
Name: 26, dtype: object

In [275]:
categorical_columns = ['workclass','education','marital-status','occupation','relationship','race','sex','native-country','salary']

In [291]:
for i in categorical_columns:
    data[i] = pd.Categorical(data[i]).codes

In [290]:
data.columns = data.columns.str.lstrip()

In [293]:
data['workclass'].unique()

array([6, 4, 7, 1, 2, 0, 5, 8, 3], dtype=int64)

In [297]:
data.iloc[26]

age                   54
workclass              0
fnlwgt            180211
education             15
education-num         10
marital-status         2
occupation             0
relationship           0
race                   1
sex                    1
capital-gain           0
capital-loss           0
hours-per-week        60
native-country        35
salary                 1
Name: 26, dtype: int64

In [309]:
data.mean()

age                   38.581634
workclass              3.868796
fnlwgt            189781.814373
education             10.298249
education-num         10.080590
marital-status         2.611794
occupation             6.572912
relationship           1.446376
race                   3.665848
sex                    0.669195
capital-gain        1077.615172
capital-loss          87.306511
hours-per-week        40.437469
native-country        36.718796
salary                 0.240817
dtype: float64

In [299]:
data.replace(0,data.mean())

age  workclass  fnlwgt  education  education-num  marital-status  \
0       50        6.0   83311        9.0             13        2.000000   
1       38        4.0  215646       11.0              9        2.611794   
2       53        4.0  234721        1.0              7        2.000000   
3       28        4.0  338409        9.0             13        2.000000   
4       37        4.0  284582       12.0             14        2.000000   
...    ...        ...     ...        ...            ...             ...   
32555   27        4.0  257302        7.0             12        2.000000   
32556   40        4.0  154374       11.0              9        2.000000   
32557   58        4.0  151910       11.0              9        6.000000   
32558   22        4.0  201490       11.0              9        4.000000   
32559   52        5.0  287927       11.0              9        2.000000   

       occupation  relationship  race       sex  capital-gain  capital-loss  \
0             4.0      1.446376   4.0  1.000000   1077.615172     87.306511   
1             6.0      1.000000   4.0  1.000000   1077.615172     87.306511   
2             6.0      1.446376   2.0  1.000000   1077.615172     87.306511   
3            10.0      5.000000   2.0  0.669195   1077.615172     87.306511   
4             4.0      5.000000   4.0  0.669195   1077.615172     87.306511   
...           ...           ...   ...       ...           ...           ...   
32555        13.0      5.000000   4.0  0.669195   1077.615172     87.306511   
32556         7.0      1.446376   4.0  1.000000   1077.615172     87.306511   
32557         1.0      4.000000   4.0  0.669195   1077.615172     87.306511   
32558         1.0      3.000000   4.0  1.000000   1077.615172     87.306511   
32559         4.0      5.000000   4.0  0.669195  15024.000000     87.306511   

       hours-per-week  native-country    salary  
0                  13            39.0  0.240817  
1                  40            39.0  0.240817  
2                  40            39.0  0.240817  
3                  40             5.0  0.240817  
4                  40            39.0  0.240817  
...               ...             ...       ...  
32555              38            39.0  0.240817  
32556              40            39.0  1.000000  
32557              40            39.0  0.240817  
32558              20            39.0  0.240817  
32559              40            39.0  1.000000  

[32560 rows x 15 columns]

In [300]:
data.head(n=7)

age  workclass  fnlwgt  education  education-num  marital-status  \
0   50          6   83311          9             13               2   
1   38          4  215646         11              9               0   
2   53          4  234721          1              7               2   
3   28          4  338409          9             13               2   
4   37          4  284582         12             14               2   
5   49          4  160187          6              5               3   
6   52          6  209642         11              9               2   

   occupation  relationship  race  sex  capital-gain  capital-loss  \
0           4             0     4    1             0             0   
1           6             1     4    1             0             0   
2           6             0     2    1             0             0   
3          10             5     2    0             0             0   
4           4             5     4    0             0             0   
5           8             1     2    0             0             0   
6           4             0     4    1             0             0   

   hours-per-week  native-country  salary  
0              13              39       0  
1              40              39       0  
2              40              39       0  
3              40               5       0  
4              40              39       0  
5              16              23       0  
6              45              39       1

In [301]:
data.iloc[26]

age                   54
workclass              0
fnlwgt            180211
education             15
education-num         10
marital-status         2
occupation             0
relationship           0
race                   1
sex                    1
capital-gain           0
capital-loss           0
hours-per-week        60
native-country        35
salary                 1
Name: 26, dtype: int64

In [310]:
data[data['occupation']==0]['occupation'].count()

1843

In [166]:
#data.isna().sum()
#pd.isna(data['workclass']).sum()

In [303]:
from sklearn.preprocessing import StandardScaler

In [304]:
a = StandardScaler()
X = data.drop(['salary'],axis=1)

In [305]:
X = a.fit_transform(X)

In [306]:
y = data['salary']

AttributeError: 'numpy.ndarray' object has no attribute 'head'

In [182]:
from sklearn.model_selection import train_test_split

In [183]:
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=0,test_size=0.3)

In [184]:
from sklearn.linear_model import LogisticRegression

In [185]:
lr = LogisticRegression(solver='lbfgs',random_state=0)

In [186]:

lr.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [187]:
predict = lr.predict(X_test)

In [188]:
print("Train - ",lr.score(X_train,y_train))
print("Test - ",lr.score(X_test,y_test))

Train -  0.8241926991926992
Test -  0.8264742014742015


In [160]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test,predict))

              precision    recall  f1-score   support

           0       0.85      0.94      0.89      7454
           1       0.71      0.45      0.55      2314

    accuracy                           0.83      9768
   macro avg       0.78      0.70      0.72      9768
weighted avg       0.81      0.83      0.81      9768



In [135]:
data.describe()

age     workclass        fnlwgt     education  education-num  \
count  32560.000000  32560.000000  3.256000e+04  32560.000000   32560.000000   
mean      38.581634      3.868796  1.897818e+05     10.298249      10.080590   
std       13.640642      1.455879  1.055498e+05      3.870317       2.572709   
min       17.000000      0.000000  1.228500e+04      0.000000       1.000000   
25%       28.000000      4.000000  1.178315e+05      9.000000       9.000000   
50%       37.000000      4.000000  1.783630e+05     11.000000      10.000000   
75%       48.000000      4.000000  2.370545e+05     12.000000      12.000000   
max       90.000000      8.000000  1.484705e+06     15.000000      16.000000   

       marital-status    occupation  relationship          race           sex  \
count    32560.000000  32560.000000  32560.000000  32560.000000  32560.000000   
mean         2.611794      6.572912      1.446376      3.665848      0.669195   
std          1.506225      4.228809      1.606794      0.848817      0.470510   
min          0.000000      0.000000      0.000000      0.000000      0.000000   
25%          2.000000      3.000000      0.000000      4.000000      0.000000   
50%          2.000000      7.000000      1.000000      4.000000      1.000000   
75%          4.000000     10.000000      3.000000      4.000000      1.000000   
max          6.000000     14.000000      5.000000      4.000000      1.000000   

       capital-gain  capital-loss  hours-per-week  native-country  \
count  32560.000000  32560.000000    32560.000000    32560.000000   
mean    1077.615172     87.306511       40.437469       36.718796   
std     7385.402999    402.966116       12.347618        7.823892   
min        0.000000      0.000000        1.000000        0.000000   
25%        0.000000      0.000000       40.000000       39.000000   
50%        0.000000      0.000000       40.000000       39.000000   
75%        0.000000      0.000000       45.000000       39.000000   
max    99999.000000   4356.000000       99.000000       41.000000   

             salary  
count  32560.000000  
mean       0.240817  
std        0.427586  
min        0.000000  
25%        0.000000  
50%        0.000000  
75%        0.000000  
max        1.000000

In [194]:
def k_vs_error_graph():
    knn_error = []
    for i in range(2,10):
        knn = KNeighborsClassifier(n_neighbors=i)
        knn.fit(X_train,y_train)
        knn_predict= knn.predict(X_test)
        knn_error.append(np.mean(y_test!=knn_predict))
    plt.plot(range(2,50),knn_error)
    plt.xlabel("K value")
    plt.ylabel("Error")

In [193]:
neighbors={'n_neighbors':np.array(range(2,10))}
knn_grid=GridSearchCV(KNeighborsClassifier(),neighbors,verbose=4,refit=True,cv=3)
knn_grid.fit(X_train,y_train)
knn_predict = knn_grid.predict(X_test)

Fitting 3 folds for each of 8 candidates, totalling 24 fits
[CV] n_neighbors=2 ...................................................


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


[CV] ....................... n_neighbors=2, score=0.812, total=   3.9s
[CV] n_neighbors=2 ...................................................


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    3.8s remaining:    0.0s


[CV] ....................... n_neighbors=2, score=0.811, total=   3.4s
[CV] n_neighbors=2 ...................................................


[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    7.2s remaining:    0.0s


[CV] ....................... n_neighbors=2, score=0.814, total=   3.5s
[CV] n_neighbors=3 ...................................................


[Parallel(n_jobs=1)]: Done   3 out of   3 | elapsed:   10.7s remaining:    0.0s


[CV] ....................... n_neighbors=3, score=0.820, total=   4.4s
[CV] n_neighbors=3 ...................................................
[CV] ....................... n_neighbors=3, score=0.815, total=   3.7s
[CV] n_neighbors=3 ...................................................
[CV] ....................... n_neighbors=3, score=0.821, total=   3.8s
[CV] n_neighbors=4 ...................................................
[CV] ....................... n_neighbors=4, score=0.825, total=   4.1s
[CV] n_neighbors=4 ...................................................
[CV] ....................... n_neighbors=4, score=0.826, total=   3.9s
[CV] n_neighbors=4 ...................................................
[CV] ....................... n_neighbors=4, score=0.823, total=   4.1s
[CV] n_neighbors=5 ...................................................
[CV] ....................... n_neighbors=5, score=0.828, total=   4.5s
[CV] n_neighbors=5 ...................................................
[CV] .

[Parallel(n_jobs=1)]: Done  24 out of  24 | elapsed:  1.7min finished


In [198]:
printaccuracy(y_test,knn_predict)

[[6787  667]
 [ 974 1340]]
              precision    recall  f1-score   support

           0       0.87      0.91      0.89      7454
           1       0.67      0.58      0.62      2314

    accuracy                           0.83      9768
   macro avg       0.77      0.74      0.76      9768
weighted avg       0.83      0.83      0.83      9768



In [197]:
def printaccuracy(y_test,predict):
    print(confusion_matrix(y_test,predict))
    print(classification_report(y_test,predict))

In [199]:
def normalizedata(X):
    SS = StandardScaler()
    X = SS.fit_transform(X)
    print("Normalization done")

Training SVM model

In [200]:
svm = SVC(kernel='rbf',random_state=0)

In [221]:
params = { 'C' : np.logspace(0, 3, 4), 'gamma' : np.logspace(-2, 1, 4)}
svm_grid = GridSearchCV(svm, params, verbose=1, cv=3,return_train_score=True)

In [222]:
svm_grid.fit(X_train,y_train)

Fitting 3 folds for each of 16 candidates, totalling 48 fits


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  48 out of  48 | elapsed: 20.2min finished


GridSearchCV(cv=3, error_score='raise-deprecating',
             estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='auto_deprecated', kernel='rbf', max_iter=-1,
                           probability=False, random_state=0, shrinking=True,
                           tol=0.001, verbose=False),
             iid='warn', n_jobs=None,
             param_grid={'C': array([   1.,   10.,  100., 1000.]),
                         'gamma': array([ 0.01,  0.1 ,  1.  , 10.  ])},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=True,
             scoring=None, verbose=1)

In [223]:
svm_predict = svm_grid.predict(X_test)

In [225]:
svm_grid.best_params_

{'C': 100.0, 'gamma': 0.01}

In [227]:
svm_grid.best_score_

0.8475342225342225

In [228]:
printaccuracy(y_test,svm_predict)

[[6995  459]
 [1013 1301]]
              precision    recall  f1-score   support

           0       0.87      0.94      0.90      7454
           1       0.74      0.56      0.64      2314

    accuracy                           0.85      9768
   macro avg       0.81      0.75      0.77      9768
weighted avg       0.84      0.85      0.84      9768



Decison tree

In [206]:
dt = DecisionTreeClassifier()

In [207]:
dt.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [209]:
dt_predict = dt.predict(X_test)

In [210]:
printaccuracy(y_test,dt_predict)

[[6481  973]
 [ 904 1410]]
              precision    recall  f1-score   support

           0       0.88      0.87      0.87      7454
           1       0.59      0.61      0.60      2314

    accuracy                           0.81      9768
   macro avg       0.73      0.74      0.74      9768
weighted avg       0.81      0.81      0.81      9768



In [211]:
rf = RandomForestClassifier()

In [216]:
params = { 'n_estimators' : np.arange(10,100,10), 'max_depth' : np.arange(5,50,5)}
rf_grid = GridSearchCV(rf, params, verbose=1, cv=2)

In [217]:
rf_grid.fit(X_train,y_train)

Fitting 2 folds for each of 81 candidates, totalling 162 fits


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done 162 out of 162 | elapsed: 16.2min finished


GridSearchCV(cv=2, error_score='raise-deprecating',
             estimator=RandomForestClassifier(bootstrap=True, class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features='auto',
                                              max_leaf_nodes=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              n_estimators='warn', n_jobs=None,
                                              oob_score=False,
                                              random_state=None, verbose=0,
                                              warm_start=False),
             iid

In [219]:
rf_predict = rf_grid.predict(X_test)

In [239]:
printaccuracy(y_test,rf_predict)

[[7064  390]
 [ 927 1387]]
              precision    recall  f1-score   support

           0       0.88      0.95      0.91      7454
           1       0.78      0.60      0.68      2314

    accuracy                           0.87      9768
   macro avg       0.83      0.77      0.80      9768
weighted avg       0.86      0.87      0.86      9768



Adaboost

In [240]:
ab = AdaBoostClassifier()

In [241]:
params = { 'n_estimators' : np.arange(10,100,10)}
ab_grid = GridSearchCV(ab, params, verbose=1, cv=3)

In [242]:
ab_grid.fit(X_train,y_train)

Fitting 3 folds for each of 9 candidates, totalling 27 fits


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  27 out of  27 | elapsed:   12.3s finished


GridSearchCV(cv=3, error_score='raise-deprecating',
             estimator=AdaBoostClassifier(algorithm='SAMME.R',
                                          base_estimator=None,
                                          learning_rate=1.0, n_estimators=50,
                                          random_state=None),
             iid='warn', n_jobs=None,
             param_grid={'n_estimators': array([10, 20, 30, 40, 50, 60, 70, 80, 90])},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=1)

In [243]:
ab_predict = ab_grid.predict(X_test)

In [244]:

printaccuracy(y_test,ab_predict)

[[7003  451]
 [ 882 1432]]
              precision    recall  f1-score   support

           0       0.89      0.94      0.91      7454
           1       0.76      0.62      0.68      2314

    accuracy                           0.86      9768
   macro avg       0.82      0.78      0.80      9768
weighted avg       0.86      0.86      0.86      9768



#GNB

In [245]:
gnb = GaussianNB()

In [246]:
gnb.fit(X_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [247]:
gnb_predict = gnb.predict(X_test)

In [248]:
printaccuracy(y_test,gnb_predict)

[[7102  352]
 [1532  782]]
              precision    recall  f1-score   support

           0       0.82      0.95      0.88      7454
           1       0.69      0.34      0.45      2314

    accuracy                           0.81      9768
   macro avg       0.76      0.65      0.67      9768
weighted avg       0.79      0.81      0.78      9768



Neural networks

In [250]:
nn = MLPClassifier(solver='sgd',random_state=0)

In [251]:
params = {
    'hidden_layer_sizes': np.arange(50,150,20),
    'learning_rate': ['constant','adaptive'],
    'max_iter': np.arange(200,300,50)
}

In [252]:
nn_grid = GridSearchCV(nn, params, cv=3)

In [253]:
nn_grid.fit(X_train,y_train)

C:\Users\Aravind Reddy\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
C:\Users\Aravind Reddy\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
C:\Users\Aravind Reddy\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
C:\Users\Aravind Reddy\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged 

GridSearchCV(cv=3, error_score='raise-deprecating',
             estimator=MLPClassifier(activation='relu', alpha=0.0001,
                                     batch_size='auto', beta_1=0.9,
                                     beta_2=0.999, early_stopping=False,
                                     epsilon=1e-08, hidden_layer_sizes=(100,),
                                     learning_rate='constant',
                                     learning_rate_init=0.001, max_iter=200,
                                     momentum=0.9, n_iter_no_change=10,
                                     nesterovs_momentum=True, power_t=0.5,
                                     random_state=0, shuffle=True, solver='sgd',
                                     tol=0.0001, validation_fraction=0.1,
                                     verbose=False, warm_start=False),
             iid='warn', n_jobs=None,
             param_grid={'hidden_layer_sizes': array([ 50,  70,  90, 110, 130]),
                         '

In [312]:
nn_predict = nn_grid.predict(X_test)

In [313]:

printaccuracy(y_test,nn_predict)

[[6981  473]
 [ 982 1332]]
              precision    recall  f1-score   support

           0       0.88      0.94      0.91      7454
           1       0.74      0.58      0.65      2314

    accuracy                           0.85      9768
   macro avg       0.81      0.76      0.78      9768
weighted avg       0.84      0.85      0.84      9768

